import { createRouter, expressWrapper } from "next-connect";
const router = createRouter();
const { GoogleSpreadsheet } = require("google-spreadsheet");
const credentials = require("../../libs/double-vision-349202-5771a423fb16.json"); // Replace with actual path
import { JWT } from "google-auth-library";
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: credentials.client_email,
  key: credentials.private_key,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const doc = new GoogleSpreadsheet(
  "10ufxNKj1GC3cYkihSzVx-alrviUpQjNTYUzme9-13GM",
  serviceAccountAuth
); // Replace with your spreadsheet ID

async function accessSpreadsheet(uploadObject) {
  //   await doc.useServiceAccountAuth(credentials);
  await doc.loadInfo(); // loads document properties and worksheets

  const sheet = doc.sheetsByIndex[0]; // assumes it's the first sheet

  // Append data
  await sheet.addRow(uploadObject);
}

router.post(async (req, res) => {
  try {
    await accessSpreadsheet(req.body);
    res.send({ status: true });
  } catch (error) {
    res.send({ status: false });
  }
});
export default router.handler({
  onError: (err, req, res) => {
    console.error(err.stack);
    res.status(err.statusCode || 500).end(err.message);
  },
});
